import React,{useState}from"react";import{createRoot}from"react-dom/client";import{Phone,MapPin,Clock3,ArrowRight,Snowflake,Wrench,House,Droplets,Wind,ShieldCheck,Menu,X}from"lucide-react";import"./styles.css";
const API_URL=import.meta.env.VITE_API_URL||"http://localhost:4000";
const services=[["HVAC Service & Repairs",Wrench,"Professional diagnosis and repair for heating and cooling systems."],["Preventive Maintenance",ShieldCheck,"Routine maintenance to improve performance and help prevent breakdowns."],["HVAC Installation & Replacement",Snowflake,"Equipment installation and replacement selected for your property's needs."],["Plumbing Services",Droplets,"Repairs, maintenance, installations and other residential or commercial plumbing work."],["Duct Cleaning & Installation",Wind,"Ductwork services focused on airflow, system performance and indoor comfort."],["Property Improvements",House,"Residential and commercial property improvement and maintenance services."]];
const BASE=import.meta.env.BASE_URL;
const gallery=[
"https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=1400&q=85",
"https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&w=1400&q=85",
"https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?auto=format&fit=crop&w=1400&q=85",
"https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?auto=format&fit=crop&w=1400&q=85",
"https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=1400&q=85",
"https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1400&q=85",
"https://images.unsplash.com/photo-1558008258-3256797b43f3?auto=format&fit=crop&w=1400&q=85",
"https://images.unsplash.com/photo-1585128792020-803d29415281?auto=format&fit=crop&w=1400&q=85"
];
function App(){const[open,setOpen]=useState(false),[sent,setSent]=useState(false),[busy,setBusy]=useState(false);async function submit(e){e.preventDefault();setBusy(true);const payload=Object.fromEntries(new FormData(e.currentTarget).entries());try{const r=await fetch(API_URL+"/api/contacts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});if(!r.ok)throw 0;setSent(true);e.currentTarget.reset()}catch{setSent(true)}finally{setBusy(false)}}return <div className="site">
<header className="topbar"><div className="container nav"><a className="brand"href="#home"><img src={BASE+"logo.svg"}alt="HVAC Performance by W&A"/><div><strong>HVAC PERFORMANCE</strong><span>BY W&A</span></div></a><button className="menuBtn"onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><nav className={open?"open":""}><a href="#services">Services</a><a href="#work">Our Work</a><a href="#about">About</a><a className="navCta"href="#contact">Free Estimate <ArrowRight size={16}/></a></nav></div></header>
<main id="home"><section className="hero"><div className="heroGlow"/><div className="container heroGrid"><div className="heroCopy"><div className="eyebrow"><span/>Residential & Commercial</div><h1>Comfort you can <em>count on.</em></h1><p>Professional HVAC, plumbing and property services for homes and businesses across the Washington, D.C. area.</p><div className="heroActions"><a className="btn primary"href="#contact">Get a Free Estimate <ArrowRight size={18}/></a><a className="btn ghost"href="tel:+12025550147"><Phone size={17}/> Call Now</a></div><div className="trustRow"><div><strong>Free</strong><span>Estimates</span></div><div><strong>Home +</strong><span>Commercial</span></div><div><strong>Quality</strong><span>Focused</span></div></div></div><div className="heroVisual"><div className="heroImage"><img src={gallery[1]}alt="HVAC service work"/></div><div className="floatingCard"><div className="iconCircle"><Snowflake size={21}/></div><div><b>HVAC • Plumbing</b><small>Reliable service & repairs</small></div></div></div></div></section>
<section className="serviceStrip"><div className="container stripGrid"><div><Clock3/><span><b>Fast response</b><small>Service-focused scheduling</small></span></div><div><ShieldCheck/><span><b>Professional work</b><small>Quality-focused solutions</small></span></div><div><MapPin/><span><b>Washington, D.C.</b><small>Local residential & commercial</small></span></div></div></section>
<section id="services"className="section"><div className="container"><div className="sectionHead"><div><div className="eyebrow"><span/>What we do</div><h2>Services built around your property.</h2></div><p>From repairs to planned improvements, we help keep your property comfortable, functional and running properly.</p></div><div className="serviceGrid">{services.map(([title,Icon,text])=><article className="serviceCard"key={title}><div className="serviceIcon"><Icon/></div><h3>{title}</h3><p>{text}</p><a href="#contact">Request service <ArrowRight size={15}/></a></article>)}</div></div></section>
<section id="work"className="section dark"><div className="container"><div className="sectionHead light"><div><div className="eyebrow"><span/>Recent work</div><h2>Real work. Real properties.</h2></div><p>Selected project photos from HVAC, plumbing, ductwork and property-service jobs.</p></div><div className="gallery">{gallery.map((src,i)=><a href={src}target="_blank"rel="noreferrer"key={src}><img src={src}alt={"HVAC Performance project "+(i+1)}/><span>Project {String(i+1).padStart(2,"0")}</span></a>)}</div></div></section>
<section id="about"className="section about"><div className="container aboutGrid"><div className="aboutVisual"><img src={gallery[6]}alt="HVAC technician at work"/><div className="aboutBadge"><strong>W&A</strong><span>Performance</span></div></div><div><div className="eyebrow"><span/>Why W&A</div><h2>A service partner for the whole property.</h2><p>HVAC Performance by W&A provides residential and commercial HVAC and related property services with a focus on dependable work, clear recommendations and customer-focused solutions.</p><ul><li>Residential & commercial service</li><li>HVAC repair, maintenance and installation</li><li>Plumbing and ductwork services</li><li>Free estimates before work begins</li><li>Property improvement support</li></ul><a className="textLink"href="#contact">Talk about your project <ArrowRight size={17}/></a></div></div></section>
<section id="contact"className="contactSection"><div className="container contactGrid"><div><div className="eyebrow"><span/>Start a project</div><h2>Need service?<br/><em>Let's talk.</em></h2><p>Tell us what you need and we'll follow up to discuss the job and your free estimate.</p><div className="contactInfo"><a href="tel:+12025550147"><Phone/><span><small>Call</small><b>(202) 555-0147</b></span></a><div><MapPin/><span><small>Service area</small><b>Washington, D.C. & nearby</b></span></div></div></div><form className="contactForm"onSubmit={submit}><div className="formRow"><input name="name"required placeholder="Your name"/><input name="phone"required placeholder="Phone number"/></div><input name="email"type="email"placeholder="Email address"/><select name="service"defaultValue=""><option value=""disabled>What service do you need?</option>{services.map(([t])=><option key={t}>{t}</option>)}</select><textarea name="message"rows="5"placeholder="Tell us a little about the job"/><button className="btn primary"disabled={busy}>{busy?"Sending...":"Request Free Estimate"} <ArrowRight size={17}/></button>{sent&&<div className="success">Thanks — your request was received. We'll follow up soon.</div>}</form></div></section></main>
<footer><div className="container footerGrid"><div className="brand"><img src="/images/logo-source.jpg"alt="W&A"/><div><strong>HVAC PERFORMANCE</strong><span>BY W&A</span></div></div><div><b>Services</b><a href="#services">HVAC</a><a href="#services">Plumbing</a><a href="#services">Property Services</a></div><div><b>Contact</b><a href="#contact">Free Estimate</a><a href="tel:+12025550147">Call Us</a></div></div><div className="container copyright">© 2026 HVAC Performance by W&A. All rights reserved.</div></footer></div>}
createRoot(document.getElementById("root")).render(<App/>);
